#### Handling duplicate data

In [1]:
import pandas as pd

In [2]:
data ={"name":["a","b","c","d","a","c"],
       "eng":[8,7,5,8,8,4],
       "hindi":[2,3,4,5,2,6]
       
       }

In [3]:
df = pd.DataFrame(data)
df

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
4    a    8      2
5    c    4      6

In [17]:
# df.duplicated()

In [ ]:
# df["duplicated"] =df.duplicated()

In [11]:
# df

In [19]:
# removing duplicates

df.drop_duplicates(inplace = True)
df

  name  eng  hindi  duplicated
0    a    8      2       False
1    b    7      3       False
2    c    5      4       False
3    d    8      5       False
4    a    8      2        True
5    c    4      6       False

In [21]:
# working with real object

dataset = pd.read_csv("loan.csv")

In [22]:
dataset.shape

(100, 13)

In [23]:
dataset.drop_duplicates(inplace= True)

In [24]:
dataset.shape

(100, 13)