##### Imbalanced Dataset - when the Model is biased

##### Technique to handle
###### (1) Random Under Sampling- We will reduce the majority of the class so that it will have same no of as the minority

###### (2)Random Over Sampling - We will increase the size of minority is inactive class too the size of majority class is active.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
dataset = pd.read_csv("imbalanced_ads.csv")
dataset.head(5)

   Age  Salary  Purchased
0   56   81476          0
1   46   64811          0
2   32   56208          0
3   25   40150          1
4   38   91180          0

In [16]:
dataset["Purchased"].value_counts()

Purchased
0    395
1    105
Name: count, dtype: int64

In [32]:
x = dataset.iloc[:, :-1]
y = dataset["Purchased"]

In [26]:
# from sklearn.model_selection import train_test_split

In [27]:
# x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [28]:
# from sklearn.linear_model import LogisticRegression

In [29]:
# lr = LogisticRegression()
# lr.fit(x_train, y_train)

In [30]:
# lr.score(x_test, y_test)

In [ ]:
# from here we can see that the model is not performing well because of the imbalanced dataset
lr.predict([[25	,40150]])

c:\Users\sures\OneDrive\Desktop\python\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

##### Under Sampling

In [31]:
from imblearn.under_sampling import RandomUnderSampler

In [34]:
ru = RandomUnderSampler()
ru.fit_resample(x, y)

(     Age  Salary
 130   49   41732
 93    50   75129
 241   19   63125
 365   39   58638
 136   40   72528
 ..   ...     ...
 468   52   25287
 469   40   54387
 481   28  103524
 492   52   25415
 495   56   25951

 [210 rows x 2 columns],
 130    0
 93     0
 241    0
 365    0
 136    0
       ..
 468    1
 469    1
 481    1
 492    1
 495    1
 Name: Purchased, Length: 210, dtype: int64)

In [35]:
ru_x,ru_y = ru.fit_resample(x, y)

In [36]:
ru_x

     Age  Salary
153   28   49703
428   50   36389
327   20   71745
60    43   97052
477   51   46614
..   ...     ...
468   52   25287
469   40   54387
481   28  103524
492   52   25415
495   56   25951

[210 rows x 2 columns]

In [37]:
ru_y

153    0
428    0
327    0
60     0
477    0
      ..
468    1
469    1
481    1
492    1
495    1
Name: Purchased, Length: 210, dtype: int64

In [38]:
# lets check the large data 0 is now reduced or not
ru_y.value_counts()

Purchased
0    105
1    105
Name: count, dtype: int64

In [39]:
from sklearn.model_selection import train_test_split

In [41]:
x_train, x_test, y_train, y_test = train_test_split(ru_x,ru_y, test_size=0.2, random_state=42)

In [42]:
from sklearn.linear_model import LogisticRegression

In [44]:
lr =LogisticRegression()
lr.fit(x_train, y_train)

LogisticRegression()

In [45]:
lr.score(x_test, y_test)

0.5238095238095238

In [ ]:
# Here we can see that the model is performing well because of the balanced dataset
lr.predict([[25	,40150]])

c:\Users\sures\OneDrive\Desktop\python\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1])

##### Random Over Sampling

In [47]:
from imblearn.over_sampling import RandomOverSampler

In [48]:
ro = RandomOverSampler()
ro.fit_resample(x, y)

(     Age  Salary
 0     56   81476
 1     46   64811
 2     32   56208
 3     25   40150
 4     38   91180
 ..   ...     ...
 785   26   32763
 786   40  101264
 787   20   99252
 788   57   23596
 789   29   89896

 [790 rows x 2 columns],
 0      0
 1      0
 2      0
 3      1
 4      0
       ..
 785    1
 786    1
 787    1
 788    1
 789    1
 Name: Purchased, Length: 790, dtype: int64)

In [49]:
ro_x, ro_y = ro.fit_resample(x, y)

In [50]:
ro_y.value_counts()

Purchased
0    395
1    395
Name: count, dtype: int64

In [51]:
x_train1, x_test1, y_train1, y_test1 = train_test_split(ro_x, ro_y, test_size=0.2, random_state=42)

In [52]:
lr1 =LogisticRegression()
lr1.fit(x_train1, y_train1)

LogisticRegression()

In [53]:
lr.score(x_test1, y_test1)

0.5126582278481012

In [54]:
lr.predict([[25	,40150]])

c:\Users\sures\OneDrive\Desktop\python\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1])