# Handling missing values with Scikit Learn

In [1]:
import pandas as pd

In [3]:
dataset = pd.read_csv("Data.csv")
dataset.head(10)

   EmployeeID     Name Department   Age   Salary JoiningDate  PerformanceScore
0         101    Alice         HR  25.0  50000.0  2018-05-21               3.5
1         102      Bob         IT   NaN  60000.0  2019-08-10               NaN
2         103  Charlie        NaN  30.0      NaN  2020-01-15               4.0
3         104      NaN    Finance  28.0  58000.0         NaN               3.8
4         105      Eve         IT   NaN  62000.0  2021-03-12               NaN
5         106    Frank         HR  45.0      NaN  2017-11-01               4.5
6         107    Grace        NaN  32.0  55000.0         NaN               3.0
7         108     Hank    Finance   NaN  57000.0  2019-06-23               NaN

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EmployeeID        8 non-null      int64
 1   Name              7 non-null      object
 2   Department        6 non-null      object
 3   Age               5 non-null      float64
 4   Salary            6 non-null      float64
 5   JoiningDate       6 non-null      object
 6   PerformanceScore  5 non-null      float64
dtypes: float64(3), int64(1), object(3)
memory usage: 580.0+ bytes

In [6]:
dataset.select_dtypes(include="float64").columns

Index(['Age', 'Salary', 'PerformanceScore'], dtype='object')

In [8]:
from sklearn.impute import SimpleImputer

In [ ]:
# We are filling the Missing values by using Mean
si = SimpleImputer(strategy="mean")
si.fit_transform(dataset[['Age', 'Salary', 'PerformanceScore']])

array([[2.50e+01, 5.00e+04, 3.50e+00],
       [3.20e+01, 6.00e+04, 3.76e+00],
       [3.00e+01, 5.70e+04, 4.00e+00],
       [2.80e+01, 5.80e+04, 3.80e+00],
       [3.20e+01, 6.20e+04, 3.76e+00],
       [4.50e+01, 5.70e+04, 4.50e+00],
       [3.20e+01, 5.50e+04, 3.00e+00],
       [3.20e+01, 5.70e+04, 3.76e+00]])

In [11]:
# arranging in a dataframe
# storing the si value in a variable
ar=si.fit_transform(dataset[['Age', 'Salary', 'PerformanceScore']])
pd.DataFrame(ar,columns=dataset.select_dtypes(include="float64").columns)

    Age   Salary  PerformanceScore
0  25.0  50000.0              3.50
1  32.0  60000.0              3.76
2  30.0  57000.0              4.00
3  28.0  58000.0              3.80
4  32.0  62000.0              3.76
5  45.0  57000.0              4.50
6  32.0  55000.0              3.00
7  32.0  57000.0              3.76

In [12]:
# Now checking the missing value present or not
new_dataset=pd.DataFrame(ar,columns=dataset.select_dtypes(include="float64").columns)
new_dataset.isnull().sum()

Age                 0
Salary              0
PerformanceScore    0
dtype: int64

In [ ]:
# Here we can see the filled missing value
new_dataset

    Age   Salary  PerformanceScore
0  25.0  50000.0              3.50
1  32.0  60000.0              3.76
2  30.0  57000.0              4.00
3  28.0  58000.0              3.80
4  32.0  62000.0              3.76
5  45.0  57000.0              4.50
6  32.0  55000.0              3.00
7  32.0  57000.0              3.76

In [14]:
# how to check that given is mean of dataset
dataset["Salary"].mean()

np.float64(57000.0)