### Label Encoding

Categorical Data-:

(1)NOMINAL DATA - The data which does not have any connections between them.
(2)Ordinal Data-It has some sequence order

In [1]:
import pandas as pd

In [11]:
df = pd.DataFrame({"Name":["Ram","Shyam","Madan","Mohan","Sundar"]})
df

     Name
0     Ram
1   Shyam
2   Madan
3   Mohan
4  Sundar

In [4]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()
# We do fit_transform at same time while training and while deploying we do fit and then transform
le.fit_transform(df["Name"])

array([2, 3, 0, 1, 4])

In [12]:
# We have add this in the given dataset
df["en_Name"] =le.fit_transform(df["Name"])
df

     Name  en_Name
0     Ram        2
1   Shyam        3
2   Madan        0
3   Mohan        1
4  Sundar        4

In [13]:
# Lets work with real data
dataset = pd.read_csv("loan.csv")
dataset.head(5)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP00001,Male,Yes,2,Graduate,Yes,16337,7648,574.0,360.0,0.0,Semiurban,N
1,LP00002,NaN,No,0,Graduate,NaN,24986,9550,261.0,360.0,1.0,Rural,Y
2,LP00003,Female,Yes,0,Graduate,No,8812,5115,74.0,NaN,1.0,Semiurban,Y
3,LP00004,Female,No,3+,Graduate,No,6820,4637,629.0,180.0,1.0,Urban,Y
4,LP00005,Male,NaN,2,Not Graduate,No,14716,4854,443.0,360.0,0.0,Semiurban,N

In [26]:
# Lets check what type of data is present
dataset["Property_Area"].unique()

array([1, 0, 2])

In [23]:
# using label Encoder
la = LabelEncoder()
la.fit(dataset["Property_Area"])
la.transform(dataset["Property_Area"])

array([1, 0, 1, 2, 1, 1, 0, 1, 1, 2, 1, 1, 2, 0, 1, 1, 0, 1, 0, 1, 2, 1,
       1, 0, 2, 2, 2, 2, 0, 2, 1, 1, 1, 0, 1, 0, 1, 1, 0, 2, 2, 0, 2, 0,
       1, 0, 0, 1, 0, 1, 0, 2, 1, 2, 1, 2, 0, 0, 0, 2, 1, 1, 1, 1, 1, 0,
       1, 1, 2, 2, 2, 0, 2, 2, 1, 0, 0, 0, 1, 1, 2, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 2, 1, 2, 1, 0, 1, 1, 1, 2])

In [ ]:
# Replace the existing data like urban, rural with the numbers then(see Result in 2nd cell above)
dataset["Property_Area"] = la.transform(dataset["Property_Area"])